name: "Frigate Plate Recognizer"
description: "Tags license plates with ALPR"
version: "1.0.3"
slug: "frigate_alpr"
init: false
arch:
  - aarch64
  - amd64
  - armv7
options:
  configpath: /data/config.yml
  dbpath: /data/frigate_plate_recognizer.db
  logfile: /data/frigate_plate_recognizer.log
  snapshotpath: /data/plates
schema:
  configpath: str
  dbpath: str?
  logfile: str?
  snapshotpath: str?

