name: "Frigate Plate Recognizer"
description: "Tags license plates with ALPR"
version: "1.0.8a"
slug: "frigate_alpr"
init: false
arch:
  - aarch64
  - amd64
  - armv7
map:
  - addon_config:rw
options:
  log_level: INFO
  frigate_url: ""
  mqtt_auth: true
  camera: []
  objects: []
  watched_plates: []
  mqtt_username: ""
  mqtt_password: ""
  mqtt_server: ""
  frigate:
    main_topic: frigate
    return_topic: plate_recognizer
    frigate_plus: ""
    min_score: .8
    always_save_snapshot: false
    save_snapshots: true
    draw_box: true
    fuzzy_match: .8
  plate_recognizer:
    enabled: true
    token:
    regions: []
  code_project:
    enabled: false
schema:
  log_level: list(NOTSET|DEBUG|INFO|WARN|ERROR|CRITICAL)?
  configpath: str?
  dbpath: str?
  logfile: str?
  snapshotpath: str?
  frigate_url: url
  mqtt_server: str
  mqtt_auth: bool
  mqtt_username: str?
  mqtt_password: password?
  watched_plates:
      - str?
  camera: 
      - str
  objects:
      - str
  frigate:
    main_topic: str?
    return_topic: str?
    frigate_plus: bool?
    min_score: float?
    always_save_snapshot: bool?
    save_snapshots: bool?
    draw_box: bool?
    fuzzy_match: float?
  plate_recognizer:
    enabled: bool?
    token: password?
    regions: 
      - str?
  code_project:
    enabled: bool?
    api_url: url?
  
services:
  - "mqtt:need"
