name: "Frigate Plate Recognizer"
description: "Tags license plates with ALPR"
version: "2.2.1"
slug: "frigate_alpr"
init: false
arch:
  - aarch64
  - amd64
  - armv7
map:
  - addon_config:rw
options:
  log_level: INFO
  frigate_url: ""
  mqtt_auth: true
  camera: []
  objects: []
  watched_plates: []
  plate_recognizer_enabled: true
  plate_recognizer_regions: []
  plate_recognizer_token: ""
  code_project_enabled: false
  code_project_api_url: ""
  mqtt_username: ""
  mqtt_password: ""
  mqtt_server: ""
  frigate:
    main_topic: frigate
    return_topic: plate_recognizer
    frigate_plus: ""
    min_score: .8
    license_plate_min_score: 0
    always_save_snapshot: false
    save_snapshots: true
    draw_box: true
    fuzzy_match: .8
    max_attempts: 3
schema:
  log_level: list(NOTSET|DEBUG|INFO|WARN|ERROR|CRITICAL)?
  frigate_url: url
  mqtt_server: str
  mqtt_auth: bool
  mqtt_username: str?
  mqtt_password: password?
  watched_plates:
      - str?
  camera: 
      - str
  objects:
      - str
  frigate:
    main_topic: str?
    return_topic: str?
    frigate_plus: bool?
    min_score: float?
    license_plate_min_score: float?
    always_save_snapshot: bool?
    save_snapshots: bool?
    draw_box: bool?
    fuzzy_match: float?
    max_attempts: float?
  plate_recognizer_enabled: bool
  plate_recognizer_regions:
    - str?
  plate_recognizer_token: password?
  code_project_enabled: bool
  code_project_api_url: password?
  
services:
  - "mqtt:need"
